project_id = "uqwpvqgstxtevhifgurb"

[functions.update-file-status]
verify_jwt = false

[functions.elevenlabs-voices]
verify_jwt = false

[functions.trigger-generation]
verify_jwt = false

[functions.update-actor-status]
verify_jwt = false

[functions.update-speech-status]
verify_jwt = false

[functions.update-animate-status]
verify_jwt = false
